### ISSUE TITLE
Notice on every page

### ISSUE THREAD

**Issue by tristanleboss** [markoheijnen/tabify-edit-screen#62] opened 2016-10-11 23:27 UTC
Hello,

It seems a piece of code is triggering the display of a PHP notice on all my admin pages.

Trying to get property of non-object    1   wp-content/plugins/tabify-edit-screen/features/plugin-support/plugin-support.php:8

The culprit is this code:

```
    $screen = get_current_screen();

    if ( 'settings_page_tabify-edit-screen' != $screen->base ) {
        return;
    }
```

get_current_screen can return NULL... https://developer.wordpress.org/reference/functions/get_current_screen/

So, the if should check if $screen is an object or at least different from null before trying to access any propoerty.

**Comment by tristanleboss** [comment] 2016-10-11 23:30
Inetrestingly enough, this warning also appears on the 'settings_page_tabify-edit-screen' page. So, it seems current_screen is not yet initialized/available when this function get called.

**Comment by markoheijnen** [comment] 2016-10-11 23:35
It could be that a plugin is doing something weird as I do test my code out but it could be that in the latest version something got changed. This is something I haven't tested yet.

I will check it out next week.

**Comment by tristanleboss** [comment] 2016-10-11 23:38
Ok, the trace I have leading to the error (thanks to Query Monitor plugin):

Tabify_Edit_Screen_Feature_Plugin_Support->__construct()
 wp-content/plugins/tabify-edit-screen/tabify-edit-screen.php:77
Tabify_Edit_Screen->load_features()
 Unknown location
do_action('admin_init')
 wp-admin/admin.php:154

**Comment by markoheijnen** [comment] 2016-10-11 23:40
I assume you are using WordPress 4.6.1 and Tabify Edit Screen 0.9.5?

**Comment by markoheijnen** [comment] 2016-10-11 23:51
Which plugins do you have activated?

**Comment by tristanleboss** [comment] 2016-10-12 03:53
Yep, I always use the last version. I have plenty of plugins but from the trace I have, I don't think a plugin is the culprit.

Everything goes according to what you coded, it just seems the global variable `$current_screen` is not available when `admin_init` action is fired. Indeed, in `./wp-admin/admin.php`, the `do_action('admin_init')` call is line #154 and the call to `set_current_screen` which create the `$current_screen` global variable is line #187.

**Comment by markoheijnen** [comment] 2016-10-18 09:51
I know a plugin is the culprit as I have seen this behavior before. A plugin can use set_current_screen() themselves as well and set it to null. Any guidance for me to reproduce it would be great.

**Comment by markoheijnen** [comment] 2016-10-25 16:52
@tristanleboss Without a list of all the plugins, I can't really help with this issue as I can't reproduce it.

**Comment by markoheijnen** [comment] 2016-11-16 23:58
Closing after no feedback.

**Closed by markoheijnen** 2016-11-16 23:58 UTC
